name: Unit test Go code

on:
  push:
    tags:
      - v*
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.21.x ]
        os: [ ubuntu-latest ]
    name: Checking
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: run tests
        run: go test ./...
