name: Linux Build & Unit tests

on:
  push:
    branches: [ "v2" ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    name: Checking
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
